// src/llm/generator.ts
import { LLMProvider, LLMProviderFactory, LLMMessage } from './providers';
import { PipelineBuilder } from '../pipeline/builder';
import { PipelineConfig } from '../types';

export interface GeneratorConfig {
    provider: 'openai' | 'anthropic' | 'groq' | 'openrouter' | 'local' | 'gemini';
    apiKey?: string;
    model?: string;
    baseURL?: string;
}

export interface GeneratedPipeline {
    name: string;
    description: string;
    code: string;
    pipeline?: PipelineBuilder;  // ✅ Add actual PipelineBuilder instance
    transformations: string[];
    estimatedCost?: string;
    provider: string;
    model: string;
    libraryVersion: string;
    timestamp: string;
}

const SYSTEM_PROMPT = `You are an expert in @async-fusion/data, a Node.js streaming library for Kafka and Spark.

Generate pipeline code based on user descriptions. Follow these rules:

1. Always use the PipelineBuilder class
2. Include proper error handling
3. Add meaningful comments
4. Use appropriate source/sink types (kafka, file, console, database)
5. Include transformations like filter, map, groupBy, window when relevant
6. Return ONLY the code block, no explanations

Available methods:
- .source(type, config) - Add data source
- .transform(fn) - Add transformation
- .sink(type, config) - Add output destination
- .enableDashboard(port) - Enable live monitoring
- .run() - Execute pipeline

Example response format:
\`\`\`javascript
const { PipelineBuilder } = require('@async-fusion/data');

const pipeline = new PipelineBuilder({ name: 'example' })
    .source('kafka', { topic: 'input', brokers: ['localhost:9092'] })
    .transform(data => ({ ...data, processed: true }))
    .sink('console', {});

pipeline.run();
\`\`\``;

export class LLMPipelineGenerator {
    private provider: LLMProvider;
    private providerName: string;
    private model: string;
    private libraryVersion: string;

    constructor(config: GeneratorConfig, libraryVersion: string) {
        this.provider = LLMProviderFactory.createProvider(config.provider, {
            apiKey: config.apiKey,
            model: config.model,
            baseURL: config.baseURL
        });
        this.providerName = config.provider;
        this.model = config.model || this.getDefaultModel(config.provider);
        this.libraryVersion = libraryVersion;  // ✅ Use passed version
    }

    private getDefaultModel(provider: string): string {
        switch (provider) {
            case 'openai': return 'gpt-3.5-turbo';
            case 'anthropic': return 'claude-3-haiku-20240307';
            case 'groq': return 'llama3-70b-8192';
            case 'openrouter': return 'openai/gpt-3.5-turbo';
            case 'local': return 'llama2';
            case 'gemini': return 'gemini-2.0-flash';
            default: return 'gpt-3.5-turbo';
        }
    }

    private getVersionPreamble(): string {
        return `// Generated by @async-fusion/data v${this.libraryVersion}
// LLM Provider: ${this.providerName}
// Model: ${this.model}
// Timestamp: ${new Date().toISOString()}

const { PipelineBuilder, version } = require('@async-fusion/data');

// Version compatibility check
if (version !== '${this.libraryVersion}') {
    console.warn(\`Warning: This pipeline was generated for v${this.libraryVersion} but running on v\${version}\`);
    console.warn('Some features may not work as expected');
}
`;
    }

    async generateFromDescription(description: string): Promise<GeneratedPipeline> {
        const messages: LLMMessage[] = [
            { role: 'system', content: SYSTEM_PROMPT },
            { role: 'user', content: `Generate a pipeline for: ${description}` }
        ];

        const response = await this.provider.generate(messages);
        
        // Extract code from response
        const rawCode = this.extractCode(response.content);
        const code = this.getVersionPreamble() + '\n' + rawCode;
        const transformations = this.extractTransformations(code);
        const name = this.extractPipelineName(description);

        // ✅ NEW: Parse the generated code and create an actual PipelineBuilder instance
        const pipeline = await this.createPipelineFromCode(rawCode, name);

        return {
            name,
            description,
            code,
            pipeline,  // ✅ Returns actual PipelineBuilder instance
            transformations,
            provider: this.providerName,
            model: this.model,
            libraryVersion: this.libraryVersion,
            timestamp: new Date().toISOString()
        };
    }

    // ✅ NEW METHOD: Create actual PipelineBuilder from generated code
    private async createPipelineFromCode(code: string, name: string): Promise<PipelineBuilder> {
        // Create a new pipeline instance
        const pipeline = new PipelineBuilder({ name });
        
        // Parse the code to extract configuration
        // This is a simplified parser - in production, you'd want more robust parsing
        
        // Extract source configurations
        const sourceMatches = code.matchAll(/\.source\(['"]([^'"]+)['"],\s*\{([^}]+)\}/g);
        for (const match of sourceMatches) {
            const sourceType = match[1];
            const sourceConfig = this.parseConfig(match[2]);
            pipeline.source(sourceType as any, sourceConfig);
        }
        
        // Extract transform functions
        const transformMatches = code.matchAll(/\.transform\(\(([^)]+)\)\s*=>\s*\{([^}]+)\}\)/g);
        for (const match of transformMatches) {
            // Create a dynamic transform function
            const transformBody = match[2].trim();
            const transformFn = new Function('data', `
                try {
                    ${transformBody}
                    return data;
                } catch (error) {
                    console.error('Transform error:', error);
                    return null;
                }
            `) as (data: any) => any;
            pipeline.transform(transformFn);
        }
        
        // Extract sink configurations
        const sinkMatches = code.matchAll(/\.sink\(['"]([^'"]+)['"],\s*\{([^}]+)\}/g);
        for (const match of sinkMatches) {
            const sinkType = match[1];
            const sinkConfig = this.parseConfig(match[2]);
            pipeline.sink(sinkType as any, sinkConfig);
        }
        
        // Check if dashboard is enabled
        if (code.includes('.enableDashboard')) {
            const portMatch = code.match(/\.enableDashboard\((\d+)\)/);
            const port = portMatch ? parseInt(portMatch[1]) : 3000;
            pipeline.enableDashboard(port);
        }
        
        return pipeline;
    }

    // ✅ Helper to parse config objects from code
    private parseConfig(configStr: string): Record<string, any> {
        const config: Record<string, any> = {};
        
        // Parse key-value pairs
        const pairs = configStr.match(/(\w+):\s*([^,}\n]+)/g);
        if (pairs) {
            for (const pair of pairs) {
                const [key, value] = pair.split(':').map(s => s.trim());
                // Remove quotes from string values
                const parsedValue = value.replace(/^['"]|['"]$/g, '');
                // Try to parse numbers
                const numValue = parseFloat(parsedValue);
                config[key] = isNaN(numValue) ? parsedValue : numValue;
            }
        }
        
        return config;
    }

    private extractCode(content: string): string {
        // Extract code between ```javascript and ``` blocks
        const codeMatch = content.match(/```(?:javascript|js)?\n([\s\S]*?)```/);
        if (codeMatch) {
            return codeMatch[1].trim();
        }
        // If no code block, return the whole content (might be just code)
        return content.trim();
    }

    private extractTransformations(code: string): string[] {
        const transformations: string[] = [];
        const transformMatches = code.matchAll(/\.transform\(([^)]+)\)/g);
        for (const match of transformMatches) {
            transformations.push(match[1].trim());
        }
        return transformations;
    }

    private extractPipelineName(description: string): string {
        // Generate a slug from the description
        const words = description.split(' ').slice(0, 5);
        return words.join('-').toLowerCase().replace(/[^a-z0-9-]/g, '');
    }

    async saveToFile(code: string, filename?: string): Promise<string> {
        const fs = require('fs');
        const path = require('path');
        const actualFilename = filename || `pipeline-${Date.now()}.js`;
        const filepath = path.join(process.cwd(), actualFilename);
        fs.writeFileSync(filepath, code);
        return filepath;
    }

    async executeGenerated(code: string): Promise<any> {
        // Create a temporary file and execute
        const filepath = await this.saveToFile(code, `temp-${Date.now()}.js`);
        const { exec } = require('child_process');
        const util = require('util');
        const execPromise = util.promisify(exec);
        
        try {
            const { stdout, stderr } = await execPromise(`node ${filepath}`);
            return { stdout, stderr };
        } finally {
            const fs = require('fs');
            fs.unlinkSync(filepath);
        }
    }

    // ✅ NEW: Direct execution without saving to file
    async runGeneratedPipeline(pipeline: PipelineBuilder): Promise<void> {
        await pipeline.run();
    }
}